DROP TABLE IF EXISTS Услуга_Косметика_12
GO
DROP TABLE IF EXISTS Автомойка_Услуга_13;
GO
DROP TABLE IF EXISTS Услуга_Заказ_19;
GO
DROP TABLE IF EXISTS Жалоба_10;
GO
DROP TABLE IF EXISTS Статус_жалобы_18;
GO
DROP TABLE IF EXISTS Заказ_5;
GO
DROP TABLE IF EXISTS Сотрудник_11;
GO
DROP TABLE IF EXISTS Бокс_2;
GO
DROP TABLE IF EXISTS Автомойка_1;
GO
DROP TABLE IF EXISTS Услуга_3;
GO
DROP TABLE IF EXISTS Косметика_4;
GO
DROP TABLE IF EXISTS Акция_7;
GO
DROP TABLE IF EXISTS Автомобиль_9;
GO
DROP TABLE IF EXISTS Клиент_8;
GO
DROP TABLE IF EXISTS Скидка_17;
GO
DROP TABLE IF EXISTS Модель_15;
GO
DROP TABLE IF EXISTS Категория_21;
GO
DROP TABLE IF EXISTS Марка_16;
GO
DROP TABLE IF EXISTS Страна_производитель_14;
GO





